### ISSUE TITLE
Stworzyć layout wydatków

### ISSUE THREAD

**Issue by IDGAFatALl** [dev-oskar/moje-auto#7]
Stwórzmy jakiś przejrzysty layout wydatków oraz zastanówmy sie co powinien zawierać.

**Comment by pjuhpl** [comment]
![Image](https://user-images.githubusercontent.com/45632214/175810552-a0b652d8-71fd-45a1-8850-8a97f783fb1a.jpg)

Został stworzony latout historii tankowania
